wandb_version: 1

train:
  desc: null
  value:
    seed: 42
    batch_size: 64
    lr: 0.0003
    warmup_steps: 1000
    steps: 100000
    weight_decay: 0.1
    max_norm: 1.0
    betas:
    - 0.9
    - 0.95
    val_items: 10
    val_every: 5000
    checkpoint_every: 5000
    log_every: 10
model:
  desc: null
  value:
    tokenizer: EleutherAI/gpt-neox-20b
    base_namename: state-spaces/mamba-130m
    dac_model_name: 44khz
    codebook_size: 1024
    n_quantizers: 3
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.37.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706276660.152443
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.16.2
      6: 4.37.1
      8:
      - 5
      13: linux-x86_64
